//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int Amount { get; set; }
        public int ReceiptNumber { get; set; }
        public int ItemId { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
